export interface Education {
  id: number
  title: string
  institution: string
  date: string
  description: string
  details?: string
  skills: string[]
  color: string
  bgColor: string
  textColor: string
  badgeBg: string
  icon: string
  category: 'diploma' | 'certification' | 'license' | 'other'
}

export const education: Education[] = [
  {
    id: 1,
    title: 'Titre RNCP De Niveau 6 - Développeur Full Stack & Data',
    institution: 'En cours',
    date: '2025',
    description:
      "Ce titre RNCP est reconnu par l'État (bac +4). Je poursuis mes études pour l'obtenir.",
    skills: ['Développement Full Stack', 'Data Science', 'Programmation', 'Base de données'],
    color: 'blue',
    bgColor: 'bg-blue-600',
    textColor: 'text-blue-600',
    badgeBg: 'bg-blue-100 text-blue-800',
    icon: '🎓',
    category: 'diploma',
  },
  {
    id: 2,
    title: 'BTS SIO (option SLAM)',
    institution: 'Lycée Paul Sabatier - Carcassonne',
    date: 'Juin 2023',
    description: 'Obtenu au lycée Paul Sabatier à Carcassonne.',
    details:
      "17/20 épreuve U5 conception et développement d'applications • 14,5/20 épreuve U6 cybersécurité des services informatiques",
    skills: [
      "Conception d'applications",
      'Développement',
      'Cybersécurité',
      'Services informatiques',
    ],
    color: 'green',
    bgColor: 'bg-green-600',
    textColor: 'text-green-600',
    badgeBg: 'bg-green-100 text-green-800',
    icon: '📚',
    category: 'diploma',
  },
  {
    id: 3,
    title: 'Certification Pix',
    institution: 'Centre de certification du lycée Paul Sabatier',
    date: '19 janvier 2023',
    description: 'Obtenu sur Pix au centre de certification du lycée Paul Sabatier.',
    skills: ['Compétences numériques', 'Informatique', 'Communication', 'Création de contenu'],
    color: 'purple',
    bgColor: 'bg-purple-600',
    textColor: 'text-purple-600',
    badgeBg: 'bg-purple-100 text-purple-800',
    icon: '🏆',
    category: 'certification',
  },
  {
    id: 4,
    title: 'Permis B',
    institution: 'Auto-école Occitanie Formation - Carcassonne',
    date: 'Janvier 2023',
    description: "Obtenu à Carcassonne dans l'auto-école Occitanie Formation.",
    skills: ['Conduite', 'Code de la route', 'Sécurité routière'],
    color: 'orange',
    bgColor: 'bg-orange-600',
    textColor: 'text-orange-600',
    badgeBg: 'bg-orange-100 text-orange-800',
    icon: '🚗',
    category: 'license',
  },
  {
    id: 5,
    title: 'Attestation MOOC',
    institution: 'SecNum Académie (ANSSI)',
    date: '18 octobre 2022',
    description: 'Obtenu sur SecNum Académie (ANSSI).',
    skills: ['Cybersécurité', 'Sécurité informatique', 'ANSSI', 'Formation en ligne'],
    color: 'red',
    bgColor: 'bg-red-600',
    textColor: 'text-red-600',
    badgeBg: 'bg-red-100 text-red-800',
    icon: '🛡️',
    category: 'certification',
  },
  {
    id: 6,
    title: 'Bac Pro Gestion Administration',
    institution: 'Lycée Charles Cros - Carcassonne',
    date: '06 juillet 2021',
    description: 'Obtenu au lycée Charles Cros à Carcassonne.',
    details: 'Mention bien avec 15,50 points sur 20,00',
    skills: ['Gestion', 'Administration', 'Bureautique', 'Communication professionnelle'],
    color: 'indigo',
    bgColor: 'bg-indigo-600',
    textColor: 'text-indigo-600',
    badgeBg: 'bg-indigo-100 text-indigo-800',
    icon: '📊',
    category: 'diploma',
  },
  {
    id: 7,
    title: "Brevet D'Études Professionnelles",
    institution: 'Lycée Charles Cros - Carcassonne',
    date: '06 juillet 2020',
    description: 'Obtenu au lycée Charles Cros à Carcassonne.',
    details: '381,00 points avec 15,24 de moyenne générale',
    skills: ['Formation professionnelle', 'Gestion', 'Administration'],
    color: 'teal',
    bgColor: 'bg-teal-600',
    textColor: 'text-teal-600',
    badgeBg: 'bg-teal-100 text-teal-800',
    icon: '📋',
    category: 'diploma',
  },
  {
    id: 8,
    title: 'Certificat Individuel De Participation À La Journée Défense Et Citoyenneté',
    institution: 'Caserne militaire de Carcassonne',
    date: '14 novembre 2018',
    description: 'Obtenu à la caserne militaire de Carcassonne.',
    skills: ['Défense', 'Citoyenneté', 'Service civique'],
    color: 'gray',
    bgColor: 'bg-gray-600',
    textColor: 'text-gray-600',
    badgeBg: 'bg-gray-100 text-gray-800',
    icon: '🎖️',
    category: 'other',
  },
  {
    id: 9,
    title: 'Diplôme National Du Brevet',
    institution: 'Collège de Cuxac-Cabardès',
    date: '12 juillet 2017',
    description: 'Obtenu au collège de Cuxac-Cabardès.',
    details: 'Mention bien avec 493,50 points sur 700,00',
    skills: ['Formation générale', 'Culture générale', 'Mathématiques', 'Français'],
    color: 'pink',
    bgColor: 'bg-pink-600',
    textColor: 'text-pink-600',
    badgeBg: 'bg-pink-100 text-pink-800',
    icon: '🎯',
    category: 'diploma',
  },
]
